### ISSUE TITLE
Which layer should we use when using the model as a general-purpose foundation model ?

### ISSUE THREAD

**Issue by vmielecnrs** [facebookresearch/HighResCanopyHeight#11]
Dear @coupriec 

Thanks to your help in Issue #4 we used your model in our projects. The idea is to use it as a general-purpose RS image encoder (a good idea?), followed by different downstream steps. In other words, considering your model is a foundation model.

However we faced a technical question: there is the parameters `out_indices` that allows for getting the embedding for selected layers. In your case, you use [a combination of layers](https://github.com/facebookresearch/HighResCanopyHeight/blob/931fe9b69a22177cb4d5c20b0b855a285f26a773/inference.py#L35C13-L35C40)  `out_indices=(9, 16, 22, 29) `, but it would be simplier for us to select a single layer output. We made tests and things get different when selecting a layer or another. What would you recommend ? The last layer ?

Many thanks for your help,
Vincent - CNRS

**Comment by coupriec** [comment]
Hi Vincent, thanks for your question, yes, I think it can be a good idea. We chose a combination of layers because it works better for dense tasks such as depth estimation. For classification tasks, we usually take the cls token, potentially concatenated with an average pooling of the last patch token layer, which can bring an small improvement in accuracy.
